### PR TITLE
Use Travis to make releases to Github

### PR DESCRIPTION
**Pull request by andreastt**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/83)

### CODE REVIEW

**Comment by andreastt** [comment]
@jgraham  Ready for review.

**Comment by andreastt** [comment]
Updated with token.

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 46 \[r2\]](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-KKAlkeluRQtTejpfJSP:-KKAlkemWqYXE3U_D0vG:-2013998697) ([raw file](https://github.com/mozilla/geckodriver/blob/a897e5f938f71024ce364d666a8c2778edcccf3c/.travis.yml#L46)):*
> ```YAML
> deploy:
>   provider: releases
>   api_key: "TOKEN"
> ```

I assume this shouldn't be the literal string "token"

---

*[.travis.yml, line 49 \[r2\]](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-KKAlwLPHke4Cdq4CvJg:-KKAlwLQLgQtwbEcK_S8:1818712167) ([raw file](https://github.com/mozilla/geckodriver/blob/a897e5f938f71024ce364d666a8c2778edcccf3c/.travis.yml#L49)):*
> ```YAML
>   skip_cleanup: true
>   file:
>     - "geckodriver-$TRAVIS_TAG.tar.gz"
> ```

I think it might be good to make these filenames match the existing scheme better?

---

*[ci.sh, line 99 \[r3\]](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-KKIt4vCxELnbgFJp71z:-KKIt4vEenHyRuychwdt:-49590082) ([raw file](https://github.com/mozilla/geckodriver/blob/6c79f7cb2c57df5154dd1a3bbdd65da33e5a3e29/ci.sh#L99)):*
> ```Shell
> 		file geckodriver-$1-$2.zip
> 	else
> 		tar zcvf geckodriver-$1-$2.tar.gz $bin
> ```

Why .tar? It's a single file so tar does nothing useful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/83)*

**Comment by jgraham** [comment]
Sorry I didn't press publish earlier. I think this is kind of OK, but I'm not thrilled about a hundred lines of shell script in the build system :/

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-:-KKIu2k8ZccFRLzjzmtx:501012895)*

**Comment by andreastt** [comment]
Shell scripts are a perfectly normal way to deal with software packaging because what you really want is some conditional behaviour, some input/output, and ability to easily run shell commands.

But as we discussed earlier, I can foresee most of this going away once we get cargo vendoring support in central or something similar to that. Although I agree it could be nice to have the packaging steps as separate commands you could run locally. I might address this in a future patch.

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ci.sh, line 99 \[r3\]](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-KKIt4vCxELnbgFJp71z:-KKJ5MNn3uLyoyPfDR_b:1589106248) ([raw file](https://github.com/mozilla/geckodriver/blob/6c79f7cb2c57df5154dd1a3bbdd65da33e5a3e29/ci.sh#L99)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Why .tar? It's a single file so tar does nothing useful.
</details>
I think what we want to do here is put it inside a directory with the version number, like we do in the `package_source` function below. I will address this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-:-KKJ4eGFTlJrWhMNBAIG:-7259282)*

**Comment by jgraham** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ci.sh, line 99 \[r3\]](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-KKIt4vCxELnbgFJp71z:-KKJFZ0YxpcmWNUq7Stw:-855935706) ([raw file](https://github.com/mozilla/geckodriver/blob/6c79f7cb2c57df5154dd1a3bbdd65da33e5a3e29/ci.sh#L99)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> I think what we want to do here is put it inside a directory with the version number, like we do in the `package_source` function below. I will address this.
</details>
I think it would be better to just zip up the file. Why would we benefit from untaring producing a file with the version number?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/83)*

**Comment by jgraham** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ci.sh, line 99 \[r3\]](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-KKIt4vCxELnbgFJp71z:-KKJFi7k0ffxOeyBTOYL:-523384161) ([raw file](https://github.com/mozilla/geckodriver/blob/6c79f7cb2c57df5154dd1a3bbdd65da33e5a3e29/ci.sh#L99)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I think it would be better to just zip up the file. Why would we benefit from untaring producing a file with the version number?
</details>
*gzip

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/83)*

**Comment by andreastt** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ci.sh, line 99 \[r3\]](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-KKIt4vCxELnbgFJp71z:-KKJNE8BTe_9Oer0fC9F:853963727) ([raw file](https://github.com/mozilla/geckodriver/blob/6c79f7cb2c57df5154dd1a3bbdd65da33e5a3e29/ci.sh#L99)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> *gzip
</details>
Because it is the standard practice when producing tarballs of programs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/83)*

**Comment by jgraham** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[ci.sh, line 99 \[r3\]](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-KKIt4vCxELnbgFJp71z:-KKNmHuCmMp4iUuXWoZz:-584163563) ([raw file](https://github.com/mozilla/geckodriver/blob/6c79f7cb2c57df5154dd1a3bbdd65da33e5a3e29/ci.sh#L99)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> Because it is the standard practice when producing tarballs of programs.
</details>
I'm still opposed to this. I don't know what value it provides to anyone, but it means that you extract extra files that aren't needed. For example chromedriver doesn't do this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/83)*

**Comment by andreastt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 49 \[r2\]](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-KKAlwLPHke4Cdq4CvJg:-KKhUKaEb7E28yQPfLeF:-499146009) ([raw file](https://github.com/mozilla/geckodriver/blob/a897e5f938f71024ce364d666a8c2778edcccf3c/.travis.yml#L49)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I think it might be good to make these filenames match the existing scheme better?
</details>
Done.

---

*[ci.sh, line 99 \[r3\]](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-KKIt4vCxELnbgFJp71z:-KKJrbNos2qFONFP8dpX:-889633000) ([raw file](https://github.com/mozilla/geckodriver/blob/6c79f7cb2c57df5154dd1a3bbdd65da33e5a3e29/ci.sh#L99)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I'm still opposed to this. I don't know what value it provides to anyone, but it means that you extract extra files that aren't needed. For example chromedriver doesn't do this.
</details>
I’ve changed the packages to include the license and readme file, which we have to ship with the program anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/83)*

**Comment by jgraham** [comment]
Reviewed 1 of 2 files at r5.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 49 \[r2\]](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-KKAlwLPHke4Cdq4CvJg:-KKiK629JtqeUK_UXktn:1764880272) ([raw file](https://github.com/mozilla/geckodriver/blob/a897e5f938f71024ce364d666a8c2778edcccf3c/.travis.yml#L49)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> Done.
</details>
I don't think this changed? I would really like names that aren't this confusing for people trying to figure out the right one to use.

---

*[ci.sh, line 99 \[r3\]](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-KKIt4vCxELnbgFJp71z:-KKiKl0v91gWUux1V5zm:19147131) ([raw file](https://github.com/mozilla/geckodriver/blob/6c79f7cb2c57df5154dd1a3bbdd65da33e5a3e29/ci.sh#L99)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> I’ve changed the packages to include the license and readme file, which we have to ship with the program anyway.
</details>
OK, I guess. But I think that gzipping up just the binary and making `--help`more useful would be a better option. I don't think there's any requirement to ship a LICENSE file. Indeed afaict the only requirement in the license that's relevant here is to tell people where they can get the source, which neither the LICENSE file nor the README.md file actually do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/83)*

**Comment by andreastt** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 49 \[r2\]](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-KKAlwLPHke4Cdq4CvJg:-KKjjkZPJvytAYk6xBwy:1255270549) ([raw file](https://github.com/mozilla/geckodriver/blob/a897e5f938f71024ce364d666a8c2778edcccf3c/.travis.yml#L49)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I don't think this changed? I would really like names that aren't this confusing for people trying to figure out the right one to use.
</details>
Okay, I forgot to change which files Travis chooses to upload, but the file names produced _on_ Travis has changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/83)*

**Comment by andreastt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 49 \[r2\]](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-KKAlwLPHke4Cdq4CvJg:-KKsH0P0l4CzXPbZbcXT:904082192) ([raw file](https://github.com/mozilla/geckodriver/blob/a897e5f938f71024ce364d666a8c2778edcccf3c/.travis.yml#L49)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> Okay, I forgot to change which files Travis chooses to upload, but the file names produced _on_ Travis has changed.
</details>
Fixed the filenames in 61e2195.

---

*[ci.sh, line 99 \[r3\]](https://reviewable.io:443/reviews/mozilla/geckodriver/83#-KKIt4vCxELnbgFJp71z:-KKsJKXmHe2EZlIHPGkq:1834327479) ([raw file](https://github.com/mozilla/geckodriver/blob/6c79f7cb2c57df5154dd1a3bbdd65da33e5a3e29/ci.sh#L99)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> OK, I guess. But I think that gzipping up just the binary and making `--help`more useful would be a better option. I don't think there's any requirement to ship a LICENSE file. Indeed afaict the only requirement in the license that's relevant here is to tell people where they can get the source, which neither the LICENSE file nor the README.md file actually do.
</details>
Okay, I’m changing it back to the way it was. I’ve filed https://github.com/mozilla/geckodriver/issues/107 to improve the `-h` text.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/83)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/83)*

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/83)*

**Comment by jgraham** [comment]
Thanks! Sorry this took so many twists and turns.

**Pull request merged**
