### PR TITLE
Print usage on error

### PR DESCRIPTION
**Pull request by andreastt**
So I decided to play a little bit with Rust again.  Here I try to get it to print errors to stderr and have the usage message dumped at the same time, like most other programs do.

Unfortunately I find that argparse either doesn’t lend itself very well to this scenario, and I couldn’t find many other examples of people doing anything but trivial things.  The other possibility is that I’m not fluent in Rust best practice.

I’m also especially unhappy with the `Vec::<u8>` on line 85, but this might be an OK approach, but I don’t know.

So @jgraham, please feel free to throw this away.

---
This change is [Reviewable](https://reviewable.io/reviews/jgraham/wires/40)

### CODE REVIEW

**Comment by andreastt** [comment]
I’m somewhat inclined to drop the whole argparse thing for getopts, which lends itself better to solve this.

**Comment by jgraham** [comment]
AIUI [clap](http://kbknapp.github.io/clap-rs/clap/index.html) is the new hotness in rust cli argument parsing

**Comment by andreastt** [comment]
I tend to like the minimalist approach that getopts takes because it doesn’t allocate much, if any, state. I think I will attempt to re-do this patch, if only for the fun of it, on the plane this afternoon.

**Comment by jgraham** [comment]
OTOH, I really dislike getopts, so would be very wary of switching to it.

**Pull request closed without merging**
