### PR TITLE
cargo: update name and repository url

### PR DESCRIPTION
**Pull request by andreastt**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/60)

### CODE REVIEW

**Comment by andreastt** [comment]
Ping @jgraham or @AutomatedTester.

**Comment by AutomatedTester** [comment]
I am going to leave this one for @jgraham as I dont know if there are crates.io things that need to be done first before we change the name

**Comment by andreastt** [comment]
Ping @jgraham.

**Comment by davehunt** [comment]
Looks like this was done in https://github.com/mozilla/geckodriver/commit/fef06db5b23ec4ef62801351c60462d88264b14d

**Pull request closed without merging**
