### PR TITLE
Make use of ? operator

### PR DESCRIPTION
**Pull request by andreastt**
No functional changes whatsoever in this PR. Replaces `try!(…)` macro with `?` operator, which helps a lot for readability in cases where multiple `try!()` macros are nested.

The linting is done through rustfmt.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/333)

### CODE REVIEW

**Comment by jgraham** [comment]
I am… not hugely a fan of `?` yet.

**Comment by andreastt** [comment]
I believe [`impl Parameters for AttributeParameters`](https://github.com/mozilla/geckodriver/pull/333/files#diff-d0fe9f4fdee74bc15b154d9b58499d8eR258) provides the best improvement in readability here, alongside cases where `try!()` causes increased indentation of multiple line statements.

As `try!()` becomes a language operator Rust feels a lot less “Lispy”, in the sense that we can get rid of a lot of wrapping `))))` parenthesis. Anyway, I’m not sure what to do to move this review forward. Can we pick out a subset of changes we agree improves readability and leave `try!()` in where we feel it adds no value?

**Comment by andreastt** [comment]
This has bitrotted, and instead of pushing one big change I suggest we do so incrementally. @jgraham mentioned that he is working on a patch to use serde (library for JSON serialisation) throughout webdriver-rust, and consequently geckodriver, so much of this code will go away soon anyway.

**Pull request closed without merging**
