### PR TITLE
Clarify Firefox support and WebDriver conformance

### PR DESCRIPTION
**Pull request by andreastt**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/129)

### CODE REVIEW

**Comment by andreastt** [comment]
@AutomatedTester r?

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/129)*

**Comment by jgraham** [comment]
Note that I really dislike the break-on-all-punctuation wrapping style. It makes the source look like some sort of unstructured poetry rather than prose, which is hard to read and imho much worse than the problem of slightly larger diffs for changes.

**Comment by andreastt** [comment]
I’ve found that [semantic linefeeds](http://rhodesmill.org/brandon/2012/one-sentence-per-line/) do wonders for collaborative editing of prose text. I guess I disagree with the readability argument too.

**Comment by jgraham** [comment]
I know someone wrote a blog post about it, but I still disagree with them :)

(arguably the underlying issue is that naive line-by-line diffs are not as suitable for prose as for code, and tools like etherpad or google docs which are able to show changes on the character level are more helpful)

**Comment by andreastt** [comment]
Yes, `git diff --word-diff` is IMO a more intelligent diffing technique to use on prose.

FWIW when I originally wrote README I did not consciously think about this, because it is how all my prose is written since Simon S. showed me nearly two and a half years ago.

**Pull request merged**
