### PR TITLE
Log listening host and port

### PR DESCRIPTION
**Pull request by andreastt**
These patches make use of the return value in webdriver::server::start introduced in webdriver-rust 0.14 by printing the host and port to stderr after we bind and the HTTPD has spun up.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/218)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main.rs, line 29 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/218#-KR0R7EPTntc6JjBl-zK:-KR0R7EQ2mFhXLAcmIDP:byg7m9s) ([raw file](https://github.com/mozilla/geckodriver/blob/e126077ce491c3342bdbd8de72e3f52dfee33f38/src/main.rs#L29)):*
> ```Rust
> }
> 
> macro_rules! print_err {
> ```

Why aren't we just using the log crate rather than creating a custom macro here? I feel like this got super-complicated for not too much benefit.

---

*[src/main.rs, line 154 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/218#-KR0QITz5v9-g9EPlzip:-KR0QIU-9w-Rl-FyN9uL:b-euc17g) ([raw file](https://github.com/mozilla/geckodriver/blob/e126077ce491c3342bdbd8de72e3f52dfee33f38/src/main.rs#L154)):*
> ```Rust
> 
>     let handler = MarionetteHandler::new(settings);
>     match webdriver::server::start(addr, handler, extension_routes()) {
> ```

    try!(webdriver::server::start([…])
           .or(Err((ExitCode::Usage, "invalid host address".to_owned())));
     print_err!("Listening on {}", listening.socket);

---

*[src/main.rs, line 158 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/218#-KR0Q3MfYixOVK2koZ69:-KR0Q3MfYixOVK2koZ6A:b-y1mmlm) ([raw file](https://github.com/mozilla/geckodriver/blob/e126077ce491c3342bdbd8de72e3f52dfee33f38/src/main.rs#L158)):*
> ```Rust
>             print_err!("listening on {}", listening.socket);
>             Ok(())
>             
> ```

Did you add trailing whitespace here? Reviewable is inscrutable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/218)*

**Comment by jgraham** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/218)*

**Comment by andreastt** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main.rs, line 154 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/218#-KR0QITz5v9-g9EPlzip:-KR46-OMMGivH5F0RjuV:b-896fix) ([raw file](https://github.com/mozilla/geckodriver/blob/e126077ce491c3342bdbd8de72e3f52dfee33f38/src/main.rs#L154)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
>     try!(webdriver::server::start([…])
>            .or(Err((ExitCode::Usage, "invalid host address".to_owned())));
>      print_err!("Listening on {}", listening.socket);
</details>
Done.

---

*[src/main.rs, line 158 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/218#-KR0Q3MfYixOVK2koZ69:-KR3fEvuKtNEFhjufX7V:b-834n6i) ([raw file](https://github.com/mozilla/geckodriver/blob/e126077ce491c3342bdbd8de72e3f52dfee33f38/src/main.rs#L158)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Did you add trailing whitespace here? Reviewable is inscrutable.
</details>
Oops.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/218)*

**Comment by andreastt** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main.rs, line 158 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/218#-KR0Q3MfYixOVK2koZ69:-KR462TfPvA8nFrGZ3I7:b-896fix) ([raw file](https://github.com/mozilla/geckodriver/blob/e126077ce491c3342bdbd8de72e3f52dfee33f38/src/main.rs#L158)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> Oops.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/218)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/218)*

**Pull request merged**
