### PR TITLE
Replace log with slog

### PR DESCRIPTION
**Pull request by andreastt**
The default log library has the disadvantage that it cannot be
reinitialised.  geckodriver needs the ability to set up the logger
again with a log level passed in with the `firefoxOptions.log.level`
capability when a new session request is made.

slog redirects calls to the log crate's `info!()`, `debug!()`, `trace!()`
&c. macros to a drain that we reinitialise when `logging::init(level:
LogLevel)` is called.

As this patch removes the env-logger crate, support for setting the
`RUST_LOG` environment variable is removed with this patch.  The correct
ways to request a log level is to use the `-vv` or `--log LEVEL` flags, or
the `firefoxOptions.log.level` capability as described in the README.md.

This patch also fixes a bug where the capability log level would
override the log level requested by flag in `MarionetteSettings`, causing
subsequent WebDriver sessions to inherit the log level.  For example,
if session 1 used `firefoxOptions.log.level` and session 2 did not,
it would reuse the level from before because `MarionetteSettings` would
not be reset.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/226)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/lib.rs, line 1 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KRcnlWCERhsu_gb_2OH:-KRcnlWD7HZVI5yI8gj0:b-3qae9g) ([raw file](https://github.com/mozilla/geckodriver/blob/f34479c875e300d9af9754a15155cbb819edff24/src/lib.rs#L1)):*
> ```Rust
> extern crate chrono;
> ```

I don't really think there is much advantage in putting this in `lib.rs` rather than just `main.rs` since we don't intend to build a library at this time.

---

*[src/logging.rs, line 119 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KRcqzthP5Iqjgsi30Rf:-KRcqztiDAA6akYz-yQn:b-g3kqij) ([raw file](https://github.com/mozilla/geckodriver/blob/f34479c875e300d9af9754a15155cbb819edff24/src/logging.rs#L119)):*
> Streamer

Could use `ASyncStreamer`, perhaps?

---

*[src/marionette.rs, line 467 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KRcuDnU9gGEKz9UCZHS:-KRcuDnVO_k4proK8Chi:b-6vpj71) ([raw file](https://github.com/mozilla/geckodriver/blob/f34479c875e300d9af9754a15155cbb819edff24/src/marionette.rs#L467)):*
> ```Rust
> 
>         self.current_log_level = options.log.level.clone().or(self.settings.log_level.clone());
>         logging::init(&self.current_log_level);
> ```

I guess this is OK, but I wonder if in the future we should cleanly separate the logging to/from various places so that the logging level to stdout only depends on the command line options, but the logging level to the log file depends on the webdriver provided setting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/226)*

**Comment by andreastt** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/lib.rs, line 1 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KRcnlWCERhsu_gb_2OH:-KRdk8jqG2-5Sbas1L7K:b-ijooc8) ([raw file](https://github.com/mozilla/geckodriver/blob/f34479c875e300d9af9754a15155cbb819edff24/src/lib.rs#L1)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I don't really think there is much advantage in putting this in `lib.rs` rather than just `main.rs` since we don't intend to build a library at this time.
</details>
It is normal practice to divide a program in an executable file and a library that is linked in (statically), even when the latter half’s purpose is not primarily geared towards library use. In fact, in the Rust world this has no practical difference apart from making us think a bit harder about API design and what functions to make public.

I think the proposed structure has the benefit of better code organisation, where UI specific bits live in _bin/geckodriver.rs_ with its own dependencies and the webdriver library’s custom handler used by the UI lives in _marionette.rs_. It’s how many Rust programs are written (rustfmt is an example), how some C programs are written, and how all Go programs are made unless they only consist of one file.

That this structure hints we intend to make a library of it, I think is a highly subtle hint.

---

*[src/logging.rs, line 119 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KRcqzthP5Iqjgsi30Rf:-KRdoOk5ZhnzZBlR5i4m:blbyt5t) ([raw file](https://github.com/mozilla/geckodriver/blob/f34479c875e300d9af9754a15155cbb819edff24/src/logging.rs#L119)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> > Streamer
> 
> Could use `ASyncStreamer`, perhaps?
</details>
Yeah, I initially wanted to use this but it was unpublished at the time.

Now that https://github.com/dpc/slog-rs/issues/43 is fixed, I’ll go ahead and make this change.

---

*[src/marionette.rs, line 467 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KRcuDnU9gGEKz9UCZHS:-KRdoZ6eSlVnUvr_UdVJ:bdsz2b0) ([raw file](https://github.com/mozilla/geckodriver/blob/f34479c875e300d9af9754a15155cbb819edff24/src/marionette.rs#L467)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I guess this is OK, but I wonder if in the future we should cleanly separate the logging to/from various places so that the logging level to stdout only depends on the command line options, but the logging level to the log file depends on the webdriver provided setting.
</details>
I had this thought too. But since we don’t support writing to file quite yet, I suggest we change it later.

But that would be my preference too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/226)*

**Comment by andreastt** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/lib.rs, line 1 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KRcnlWCERhsu_gb_2OH:-KRhn-HM3y8spo-wnESA:b-jbussd) ([raw file](https://github.com/mozilla/geckodriver/blob/f34479c875e300d9af9754a15155cbb819edff24/src/lib.rs#L1)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> It is normal practice to divide a program in an executable file and a library that is linked in (statically), even when the latter half’s purpose is not primarily geared towards library use. In fact, in the Rust world this has no practical difference apart from making us think a bit harder about API design and what functions to make public.
> 
> I think the proposed structure has the benefit of better code organisation, where UI specific bits live in _bin/geckodriver.rs_ with its own dependencies and the webdriver library’s custom handler used by the UI lives in _marionette.rs_. It’s how many Rust programs are written (rustfmt is an example), how some C programs are written, and how all Go programs are made unless they only consist of one file.
> 
> That this structure hints we intend to make a library of it, I think is a highly subtle hint.
</details>
I experimented with putting this back in _src/main.rs_ and it works fine, but I’m discouraged by the complexity of the import and use headers. To me, at least, it feels clearer when these are separated in _src/bin/geckodriver.rs_ and _src/lib.rs_.

```rust
// src/main.rs

#[macro_use]
extern crate clap;
#[macro_use]
extern crate webdriver;
extern crate chrono;
#[macro_use]
extern crate lazy_static;
extern crate hyper;
extern crate mozprofile;
extern crate mozrunner;
extern crate regex;
extern crate rustc_serialize;
#[macro_use]
extern crate slog;
extern crate slog_atomic;
extern crate slog_stdlog;
extern crate zip;

// must come after slog
#[macro_use]
extern crate log;

use clap::{App, Arg};
use std::borrow::ToOwned;
use std::io::Write;
use std::net::{SocketAddr, IpAddr};
use std::path::PathBuf;
use std::str::FromStr;

// must come before local module imports
macro_rules! try_opt {
    ($expr:expr, $err_type:expr, $err_msg:expr) => ({
        match $expr {
            Some(x) => x,
            None => return Err(WebDriverError::new($err_type, $err_msg))
        }
    })
}

mod logging;
mod marionette;

use logging::LogLevel;
use marionette::{extension_routes, MarionetteHandler, MarionetteSettings};

// … rest of src/main.rs …
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/226)*

**Comment by andreastt** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/logging.rs, line 119 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KRcqzthP5Iqjgsi30Rf:-KRhyt8H8Qd-3II9BEYa:boumick) ([raw file](https://github.com/mozilla/geckodriver/blob/f34479c875e300d9af9754a15155cbb819edff24/src/logging.rs#L119)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> Yeah, I initially wanted to use this but it was unpublished at the time.
> 
> Now that https://github.com/dpc/slog-rs/issues/43 is fixed, I’ll go ahead and make this change.
</details>
Okay, I aren’t able to figure this out. I get the following when trying to compile it with the changes:

```
% cargo build
   Compiling geckodriver v0.10.0 (file:///home/ato/1/geckodriver)
src/logging.rs:8:5: 8:24 error: unresolved import `slog_stream::Format`. Maybe a missing `extern crate slog_stream`? [E0432]
src/logging.rs:8 use slog_stream::Format;
                     ^~~~~~~~~~~~~~~~~~~
src/logging.rs:8:5: 8:24 help: run `rustc --explain E0432` to see a detailed explanation
src/logging.rs:15:5: 15:31 error: unresolved import `slog_stream::AsyncStreamer`. Maybe a missing `extern crate slog_stream`? [E0432]
src/logging.rs:15 use slog_stream::AsyncStreamer;
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

Of course I have included `extern crate slog_stream` before this file is used, so I don’t know what is happening. I think it’s worthwhile to use the `AsyncStreamer`, but it can probably wait until slog becomes a stable API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/226)*

**Comment by andreastt** [comment]
Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/logging.rs, line 119 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KRcqzthP5Iqjgsi30Rf:-KSLxlLAfLRXlkGHX5NI:bk4rho9) ([raw file](https://github.com/mozilla/geckodriver/blob/f34479c875e300d9af9754a15155cbb819edff24/src/logging.rs#L119)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> Okay, I aren’t able to figure this out. I get the following when trying to compile it with the changes:
> 
> ```
> % cargo build
>    Compiling geckodriver v0.10.0 (file:///home/ato/1/geckodriver)
> src/logging.rs:8:5: 8:24 error: unresolved import `slog_stream::Format`. Maybe a missing `extern crate slog_stream`? [E0432]
> src/logging.rs:8 use slog_stream::Format;
>                      ^~~~~~~~~~~~~~~~~~~
> src/logging.rs:8:5: 8:24 help: run `rustc --explain E0432` to see a detailed explanation
> src/logging.rs:15:5: 15:31 error: unresolved import `slog_stream::AsyncStreamer`. Maybe a missing `extern crate slog_stream`? [E0432]
> src/logging.rs:15 use slog_stream::AsyncStreamer;
>                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> Of course I have included `extern crate slog_stream` before this file is used, so I don’t know what is happening. I think it’s worthwhile to use the `AsyncStreamer`, but it can probably wait until slog becomes a stable API.
</details>
I was successfully able to upgrade slog to 1.0.0 through a bit of hackery due to slog-atomic having been updated (filed as https://github.com/dpc/slog-rs/issues/51).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/226)*

**Comment by andreastt** [comment]
Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/logging.rs, line 119 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KRcqzthP5Iqjgsi30Rf:-KSLxyCmWVS6Qdxjvr-I:b-896fix) ([raw file](https://github.com/mozilla/geckodriver/blob/f34479c875e300d9af9754a15155cbb819edff24/src/logging.rs#L119)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> I was successfully able to upgrade slog to 1.0.0 through a bit of hackery due to slog-atomic having been updated (filed as https://github.com/dpc/slog-rs/issues/51).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/226)*

**Comment by andreastt** [comment]
Updated to sloc-atomic 0.4.

**Comment by jgraham** [comment]
Reviewed 1 of 8 files at r1, 5 of 6 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[Cargo.toml, line 23 at r3](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KSm-4oNUoWCCRF5RtO7:-KSm-4oO2F25scxSAcU1:bn4467c) ([raw file](https://github.com/mozilla/geckodriver/blob/faeb63a7757e5ec4a62a1622ef0a6f596b39cdd1/Cargo.toml#L23)):*
> ```TOML
> regex = "0.1.47"
> rustc-serialize = "0.3.16"
> slog = "^1"
> ```

I feel like the `^` shouldn't be needed for a 1.0 release.

---

*[src/lib.rs, line 1 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KRcnlWCERhsu_gb_2OH:-KSm-Evpc8fGqUgxWCsD:b-yioljq) ([raw file](https://github.com/mozilla/geckodriver/blob/f34479c875e300d9af9754a15155cbb819edff24/src/lib.rs#L1)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> I experimented with putting this back in _src/main.rs_ and it works fine, but I’m discouraged by the complexity of the import and use headers. To me, at least, it feels clearer when these are separated in _src/bin/geckodriver.rs_ and _src/lib.rs_.
> 
> ```rust
> // src/main.rs
> 
> #[macro_use]
> extern crate clap;
> #[macro_use]
> extern crate webdriver;
> extern crate chrono;
> #[macro_use]
> extern crate lazy_static;
> extern crate hyper;
> extern crate mozprofile;
> extern crate mozrunner;
> extern crate regex;
> extern crate rustc_serialize;
> #[macro_use]
> extern crate slog;
> extern crate slog_atomic;
> extern crate slog_stdlog;
> extern crate zip;
> 
> // must come after slog
> #[macro_use]
> extern crate log;
> 
> use clap::{App, Arg};
> use std::borrow::ToOwned;
> use std::io::Write;
> use std::net::{SocketAddr, IpAddr};
> use std::path::PathBuf;
> use std::str::FromStr;
> 
> // must come before local module imports
> macro_rules! try_opt {
>     ($expr:expr, $err_type:expr, $err_msg:expr) => ({
>         match $expr {
>             Some(x) => x,
>             None => return Err(WebDriverError::new($err_type, $err_msg))
>         }
>     })
> }
> 
> mod logging;
> mod marionette;
> 
> use logging::LogLevel;
> use marionette::{extension_routes, MarionetteHandler, MarionetteSettings};
> 
> // … rest of src/main.rs …
> ```
</details>
Well I don't think that's a problem tbh. The same code exists however we divide it up between files. 

I strongly feel that this refactor is unrelated to the logging change, but I guess if you really want to land it without breaking things into multiple commits that's OK.

---

*[src/logging.rs, line 107 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KSm30MEm15Vz5Jj6MBU:-KSm30MFuSlCq-Wv3e1b:b-g6lbsy) ([raw file](https://github.com/mozilla/geckodriver/blob/83a3e70d4b5fa7efeac0afd3df24f27d3ec0fe5a/src/logging.rs#L107)):*
> ```Rust
>     let effective_level = level.as_ref().unwrap_or(DEFAULT_LEVEL);
> 
>     let drain = filtered_gecko_log(&effective_level);
> ```

Why isn't this needed now?

---

*[src/logging.rs, line 119 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KRcqzthP5Iqjgsi30Rf:-KSm18KNl6IQXrdCwnmN:bcfe05q) ([raw file](https://github.com/mozilla/geckodriver/blob/f34479c875e300d9af9754a15155cbb819edff24/src/logging.rs#L119)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> Done.
</details>
But this still uses `Streamer`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/226)*

**Comment by andreastt** [comment]
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[Cargo.toml, line 23 at r3](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KSm-4oNUoWCCRF5RtO7:-KSqRF6wOG7Rm_dL0fFT:b-896fix) ([raw file](https://github.com/mozilla/geckodriver/blob/faeb63a7757e5ec4a62a1622ef0a6f596b39cdd1/Cargo.toml#L23)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I feel like the `^` shouldn't be needed for a 1.0 release.
</details>
Done.

---

*[src/logging.rs, line 107 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KSm30MEm15Vz5Jj6MBU:-KSumeGOerNf3hZuQe1M:bc0a2zq) ([raw file](https://github.com/mozilla/geckodriver/blob/83a3e70d4b5fa7efeac0afd3df24f27d3ec0fe5a/src/logging.rs#L107)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Why isn't this needed now?
</details>
It was stilled needed, and I put it back. Good find.

---

*[src/logging.rs, line 119 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KRcqzthP5Iqjgsi30Rf:-KSumbcINhTnyCm3vz4F:br8objc) ([raw file](https://github.com/mozilla/geckodriver/blob/f34479c875e300d9af9754a15155cbb819edff24/src/logging.rs#L119)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> But this still uses `Streamer`?
</details>
Replaced with _AsyncStreamer_.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/226)*

**Comment by andreastt** [comment]
Review status: 3 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/lib.rs, line 1 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/226#-KRcnlWCERhsu_gb_2OH:-KSv1kHibgUxXkfTf71b:bwwprvh) ([raw file](https://github.com/mozilla/geckodriver/blob/f34479c875e300d9af9754a15155cbb819edff24/src/lib.rs#L1)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Well I don't think that's a problem tbh. The same code exists however we divide it up between files. 
> 
> I strongly feel that this refactor is unrelated to the logging change, but I guess if you really want to land it without breaking things into multiple commits that's OK.
</details>
Okay, I see no need to push this since they are functionally equivalent.

Reverted this change and elaborated the top of _src/main.rs_, which I think addresses this issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/226)*

**Comment by jgraham** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/226)*

**Pull request merged**
