### PR TITLE
Allow specifying arguments to the firefox binary through the firefox_args capability

### PR DESCRIPTION
**Pull request by jgraham**
This must be an array of strings that will be interpreted as arguments to Firefox

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/65)

### CODE REVIEW

**Comment by jgraham** [comment]
r? @andreastt 

Should geckdriver whitelist arguments?

**Comment by andreastt** [comment]
I shouldn’t think a whitelist is necessary at this point. I don’t know of any other drivers that does this.

<details><summary><i>Previously, jgraham wrote…</i></summary>
> r? @andreastt 
> 
> 
> 
> Should geckdriver whitelist arguments?
</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/marionette.rs, line 294 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/65#-KIcJBBo_cCUJFrGCOsx:-KIcJBBp-3ZwAtRv1IJJ:964412267) ([raw file](https://github.com/mozilla/geckodriver/blob/e4549f63cb75c8dce25af06ac2fc5800fe623872/src/marionette.rs#L294)):*
> ```Rust
>             BrowserLauncher::BinaryLauncher(ref binary) => {
>                 let mut runner = try!(FirefoxRunner::new(&binary, profile));
>                 if let Some(runner_args) = args {
> ```

Long variable name for a transient variable IMO.

---

*[src/marionette.rs, line 295 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/65#-KIcM1btw17FA8oFHpts:-KIcM1bvrgenBVLNb4Ds:1416750978) ([raw file](https://github.com/mozilla/geckodriver/blob/e4549f63cb75c8dce25af06ac2fc5800fe623872/src/marionette.rs#L295)):*
> ```Rust
>                 let mut runner = try!(FirefoxRunner::new(&binary, profile));
>                 if let Some(runner_args) = args {
>                     runner.args().extend_from_slice(&*runner_args);
> ```

I think `runner.args().extend(runner_args.into_iter())`is more readable.

---

*[src/marionette.rs, line 357 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/65#-KIcEeGiX4qliNMgFLIT:-KIcEeGiX4qliNMgFLIU:630737415) ([raw file](https://github.com/mozilla/geckodriver/blob/e4549f63cb75c8dce25af06ac2fc5800fe623872/src/marionette.rs#L357)):*
> ```Rust
>                             .iter()
>                             .map(|x| x.as_string().map(|x| x.to_owned()))
>                             .collect::<Option<Vec<String>>>()
> ```

I wonder if we can simplify this a bit by relying on the return type information and default str specialisation coercion:

```rust
let arr = try!(json.as_array().ok_or(
               WebDriverError::new(ErrorStatus::UnknownError, "Arguments was not an array")));
// arr is &Vec<Json>

// iterate over it,
// and for each Json that represents a string literal,
// turn it into an owned String using str specialisation,
// then collect results to vector.
let args = arr.iter().map(|s| s.to_string()).collect();

Ok(Some(args))
```

… but as far as I understand, this doesn’t (or does it?) guarantee that all elements in the array are strings?

In any case, this function is barely readable because of the nesting, so I’d prefer if we could split it into at least two statements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/65#-:-KIcESl4gne2TnziF5qQ:-172912310)*

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/marionette.rs, line 357 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/65#-KIcEeGiX4qliNMgFLIT:-KIcYp_Z3cXgQTXqITjH:-1944640048) ([raw file](https://github.com/mozilla/geckodriver/blob/e4549f63cb75c8dce25af06ac2fc5800fe623872/src/marionette.rs#L357)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> I wonder if we can simplify this a bit by relying on the return type information and default str specialisation coercion:
> 
> ```rust
> let arr = try!(json.as_array().ok_or(
>                WebDriverError::new(ErrorStatus::UnknownError, "Arguments was not an array")));
> // arr is &Vec<Json>
> 
> // iterate over it,
> // and for each Json that represents a string literal,
> // turn it into an owned String using str specialisation,
> // then collect results to vector.
> let args = arr.iter().map(|s| s.to_string()).collect();
> 
> Ok(Some(args))
> ```
> 
> … but as far as I understand, this doesn’t (or does it?) guarantee that all elements in the array are strings?
> 
> In any case, this function is barely readable because of the nesting, so I’d prefer if we could split it into at least two statements.
</details>
That doesn't work because it doesn't return an error if the things are not strings. In fact it produces a `Vec<Option<String>>` which isn't the right type at all.

I can try to clean up the formatting though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/65)*

**Comment by andreastt** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/65)*

**Pull request merged**
