### PR TITLE
Set log verbosity from capability

### PR DESCRIPTION
**Pull request by andreastt**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/217)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 3 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/marionette.rs, line 451 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/217#-KR0WQwsbbcoKpcebWmc:-KR0WQwt6vssElvu7bci:b-3x2ohx) ([raw file](https://github.com/mozilla/geckodriver/blob/a1ea7927e483a74759fe9d935be59a9a9561d713/src/marionette.rs#L451)):*
> ```Rust
>                     let s = try!(json.as_string()
>                         .ok_or(WebDriverError::new(ErrorStatus::InvalidArgument, "Log level is not a string")));
>                     let l = try!(LogLevel::from_str(s).ok()
> ```

Don't use `l` as a variable name.  Just

    Some(try!(LogLevel::from_str(s)
                        .ok()
                       .ok_or(WebDriverError::new(ErrorStatus::InvalidArgument, "Log level is unknown"))))

would be fine.

---

*[src/marionette.rs, line 460 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/217#-KR0X46EHa09neVfB46a:-KR0X46Gt44DZ6TDVCU7:b-8mf1ns) ([raw file](https://github.com/mozilla/geckodriver/blob/a1ea7927e483a74759fe9d935be59a9a9561d713/src/marionette.rs#L460)):*
> ```Rust
>             Ok(LogOptions {
>                 level: level,
>                 file: None,
> ```

It's not really clear why this is always `None`.

---

*[src/marionette.rs, line 507 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/217#-KR0Xj22e38zo3oe5Vsc:-KR0Xj23SxLKAwl21GE-:b-tbtkur) ([raw file](https://github.com/mozilla/geckodriver/blob/a1ea7927e483a74759fe9d935be59a9a9561d713/src/marionette.rs#L507)):*
> ```Rust
> }
> 
> // env_logger may only be initialised once. This function should not be
> ```

This seems troublesome because we certianly want logging before the http connection is established for diagnosing problems in geckodriver itself. Also it doesn't work if we get a second session after the first has quit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/217)*

**Comment by jgraham** [comment]
Reviewed 3 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/217)*

**Comment by andreastt** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/marionette.rs, line 451 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/217#-KR0WQwsbbcoKpcebWmc:-KR4Cg5iRgTlRNaMFN6x:b-896fix) ([raw file](https://github.com/mozilla/geckodriver/blob/a1ea7927e483a74759fe9d935be59a9a9561d713/src/marionette.rs#L451)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Don't use `l` as a variable name.  Just
> 
>     Some(try!(LogLevel::from_str(s)
>                         .ok()
>                        .ok_or(WebDriverError::new(ErrorStatus::InvalidArgument, "Log level is unknown"))))
> 
> would be fine.
</details>
Done.

---

*[src/marionette.rs, line 460 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/217#-KR0X46EHa09neVfB46a:-KR4Ci63fj4ch4QJ8o3r:b-896fix) ([raw file](https://github.com/mozilla/geckodriver/blob/a1ea7927e483a74759fe9d935be59a9a9561d713/src/marionette.rs#L460)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> It's not really clear why this is always `None`.
</details>
Done.

---

*[src/marionette.rs, line 507 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/217#-KR0Xj22e38zo3oe5Vsc:-KR4CjgWFBDohn3_NlaV:b-896fix) ([raw file](https://github.com/mozilla/geckodriver/blob/a1ea7927e483a74759fe9d935be59a9a9561d713/src/marionette.rs#L507)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> This seems troublesome because we certianly want logging before the http connection is established for diagnosing problems in geckodriver itself. Also it doesn't work if we get a second session after the first has quit.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/217)*

**Comment by jgraham** [comment]
Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/217)*

**Pull request merged**
