### PR TITLE
Set verbosity from capability

### PR DESCRIPTION
**Pull request by andreastt**
Parts of this PR will have to be re-done for #161.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/191)

### CODE REVIEW

**Comment by jgraham** [comment]
161 is basically ready to go, modulo r+ on the fixups, so I think we should land that first.

**Comment by andreastt** [comment]
That’s fine. This is probably easier to rebase.

**Comment by andreastt** [comment]
Ping @jgraham

**Comment by andreastt** [comment]
Closing this momentarily whilst I rework it do also accept an output file.

**Pull request closed without merging**
