### PR TITLE
Clean up logging before 0.9.0 release

### PR DESCRIPTION
**Pull request by andreastt**
Ensures incoming and outgoing packets are logged in the same way.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/130)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/marionette.rs, line 57 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWSWEzThoQ50U4Qa4-:-KLWSWEzThoQ50U4Qa40:644568197) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L57)):*
> ```Rust
> use zip;
> 
> #[allow(dead_code)] pub const DEFAULT_HOST: &'static str = "localhost";
> ```

This doesn't seem to be dead code? It's also arguably not a default since it's the only host permitted.

---

*[src/marionette.rs, line 58 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWSYiybnO9JktFP6JW:-KLWSYiybnO9JktFP6JX:1808809084) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L58)):*
> ```Rust
> 
> #[allow(dead_code)] pub const DEFAULT_HOST: &'static str = "localhost";
> #[allow(dead_code)] pub const DEFAULT_PORT: u16 = 2828;
> ```

I think this was better defined in the tests, or not at all since it isn't actually used anywhere.

---

*[src/marionette.rs, line 337 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWT1s5Bqow5xqO2rmm:-KLWT1s6ClsiY-kVMbm8:1020088314) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L337)):*
> ```Rust
>             } else {
>                 return Err(WebDriverError::new(ErrorStatus::UnknownError,
>                                                "Expected browser binary location, \
> ```

This isn't quite accurate, since we also try to find a default binary path.

---

*[src/marionette.rs, line 434 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWTRKiMVdUMDRKId6r:-KLWTRKiMVdUMDRKId6s:-354159552) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L434)):*
> ```Rust
>                           profile.temp_dir.as_ref().expect("Profile doesn't have a path").path()));
> 
>         // TODO(jgraham): Stop mozprofile erroring if user.js already exists
> ```

This is actually done.

---

*[src/marionette.rs, line 440 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWTYmdoMrO7GIpol4C:-KLWTYmdoMrO7GIpol4D:-1182610766) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L440)):*
> ```Rust
>     pub fn load_browser_args(&self, capabilities: &NewSessionParameters) -> WebDriverResult<Option<Vec<String>>> {
>         if let Some(args_json) = capabilities.get("firefox_args") {
>             let args_array = try!(args_json.as_array().ok_or(
> ```

I totally prefer the old indentation.

---

*[src/marionette.rs, line 480 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWToEp3nGg1HTMH8pD:-KLWToEqEAU7-M8OUEg3:1988784383) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L480)):*
> ```Rust
>                 if let Some(dir) = create_dir {
>                     if !dir.exists() {
>                         debug!("Creating directory tree {}", dir.to_string_lossy());
> ```

This doesn't make it clear what the directory is used for.

---

*[src/marionette.rs, line 554 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWU01E0C9f7TBvmYq6:-KLWU01FAGTSsw3VFWkQ:935679773) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L554)):*
> ```Rust
>         }
>         if let Some(ref mut runner) = self.browser {
>             debug!("Stopping browser");
> ```

I don't think this is an improvement.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/130)*

**Comment by andreastt** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/marionette.rs, line 57 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWSWEzThoQ50U4Qa4-:-KLWcLSkmv43aV2xF1q0:417467562) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L57)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> This doesn't seem to be dead code? It's also arguably not a default since it's the only host permitted.
</details>
Right, it’s only `DEFAULT_PORT` that is dead because it is only used when tests are compiled.

Once Marionette runs on Fennec, it _will become_ a default though, as you will need the IP of the device to connect to for Android.

This constant is currently published, but I will un-publish it so we can change its name later.

---

*[src/marionette.rs, line 58 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWSYiybnO9JktFP6JW:-KLWdTIws2ZFamWzMDgK:1825854747) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L58)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I think this was better defined in the tests, or not at all since it isn't actually used anywhere.
</details>
It totally makes sense as a constant, rather than leaving magic numbers with no meaning scattered throughout the code.

But since I’m unpublishing `DEFAULT_HOST`, I’ll move this back to the tests in _main.rs_.

---

*[src/marionette.rs, line 337 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWT1s5Bqow5xqO2rmm:-KLWe-MG98fVhEtGzs-X:862990045) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L337)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> This isn't quite accurate, since we also try to find a default binary path.
</details>
This is now true.

---

*[src/marionette.rs, line 440 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWTYmdoMrO7GIpol4C:-KLWezBQsbfiqOSzH8-t:-1507408792) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L440)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I totally prefer the old indentation.
</details>
I dislike this type of style because it relies on a variable number of space characters.

More philosophically, I dislike any style of indentation that requires human input, so I’m reverting this back to the way it was so that we can run rustfmt on it some time in the future.

---

*[src/marionette.rs, line 554 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWU01E0C9f7TBvmYq6:-KLWgFIWNXBRIXWRtK4c:1939184703) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L554)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I don't think this is an improvement.
</details>
It is, because we’re not _closing_ the browser: we’re stopping the process. “Closing a process” makes no sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/130)*

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/marionette.rs, line 58 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWSYiybnO9JktFP6JW:-KLWjU1kj19RexrNTAFr:390067067) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L58)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> It totally makes sense as a constant, rather than leaving magic numbers with no meaning scattered throughout the code.
> 
> But since I’m unpublishing `DEFAULT_HOST`, I’ll move this back to the tests in _main.rs_.
</details>
Well the way it is used at present is actually "any random unsigned 16 bit integer", so naming it is slightly unmeaningful. But OK.

---

*[src/marionette.rs, line 440 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWTYmdoMrO7GIpol4C:-KLWjp59f2BgIj_tXhDG:2085304219) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L440)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> I dislike this type of style because it relies on a variable number of space characters.
> 
> More philosophically, I dislike any style of indentation that requires human input, so I’m reverting this back to the way it was so that we can run rustfmt on it some time in the future.
</details>
I don't exactly know what you object to, but breaking long chains of method calls so that each line starts with a `.` is common here and in other rust code. I strongly believe it's the best style here.

I agree we should use rustfmt in the longer term, possibly with some non-default rules as required (rustfmt does not intend to be as opinionated as gofmt).

---

*[src/marionette.rs, line 554 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWU01E0C9f7TBvmYq6:-KLWkT5aLEfFxaEmlSQG:1805922517) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L554)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> It is, because we’re not _closing_ the browser: we’re stopping the process. “Closing a process” makes no sense.
</details>
But the noun in the message is still "browser", not "process". I agree that "Stopping browser process" would be a reasonable message, but the set of verbs that apply to applications and processes are different (and "Closing browser" is I think equally acceptable).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/130)*

**Comment by andreastt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/marionette.rs, line 440 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWTYmdoMrO7GIpol4C:-KLWq4BP_UdrGLPTRWEU:184919535) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L440)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I don't exactly know what you object to, but breaking long chains of method calls so that each line starts with a `.` is common here and in other rust code. I strongly believe it's the best style here.
> 
> I agree we should use rustfmt in the longer term, possibly with some non-default rules as required (rustfmt does not intend to be as opinionated as gofmt).
</details>
I’m not objecting to the Rust syntax. I didn’t make any functional changes.

Conceptually, I’m against _indentation styles_ that align statements that are broken up in multiple lines with an arbitrary number of space characters to align with the column position of a special-meaning character in the line above.

Since we’re already off-topic here, my opinion on indentation is that it should be a job for the computer. I have more important things to do than to align up columns.

---

*[src/marionette.rs, line 554 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/130#-KLWU01E0C9f7TBvmYq6:-KLWsmsyxqDvszvWd_ap:-2012480143) ([raw file](https://github.com/mozilla/geckodriver/blob/a190aeaaeaeb24eaeaf45a72a2bc53be9f1d8ae7/src/marionette.rs#L554)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> But the noun in the message is still "browser", not "process". I agree that "Stopping browser process" would be a reasonable message, but the set of verbs that apply to applications and processes are different (and "Closing browser" is I think equally acceptable).
</details>
But the fact is that we’re not closing the browser in any traditional meaning of the word. We’re not clicking the close button on the application, calling quit from the main menu, or sending `quitApplication` to Marionette. These are the things I associate with “closing the browser”.

If you think “Stopping browser process” is acceptable I can push a fixup for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/130)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/130)*

**Pull request merged**
