### PR TITLE
Add new --version flag showing copying info and link to repo

### LINKED ISSUE #107: Include link to source code and copying information in help text
The `-h` flag should include a link to the source code repository (this) and information on copying. This allows us to distribute the program in executable form without including a README or a COPYING file.

### PR DESCRIPTION
**Pull request by andreastt**
Fixes #107.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/109)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 2 of 6 files at r1.
Review status: 2 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[build.rs, line 11 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxTxz6vRy_3fbx1gNx:-KKxTxz7Eoa8eHFmavhm:1833142053) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/build.rs#L11)):*
> ```Rust
> use walkdir::WalkDir;
> 
> fn main() {
> ```

So this is clever, but I am concerned that it's fragile. I think it never works on Windows, and we never want to publish without this information, but there's no way to enforce that it must be set when building a release. Myabe the latter could be solved with a 

---

*[build.rs, line 34 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxS3HOKodrKrkqn-3c:-KKxS3HP_FPuDX2sfZq8:-874178330) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/build.rs#L34)):*
> ```Rust
> // Returns `None` if git is not available.
> fn git_head_sha1() -> Option<String> {
>     Command::new("git")
> ```

What about windows?

---

*[src/main.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxRJ3nAKAt69_-ae-V:-KKxRJ3oahz-72xhePPU:-1802185897) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/src/main.rs#L44)):*
> ```Rust
> mod marionette;
> 
> type ProgramResult = std::result::Result<(), String>;
> ```

Feels like this could take a `(ExitCode, String)`

---

*[src/main.rs, line 109 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxUTAHUSyG8STQQova:-KKxUTAIwNboIorGLBtp:1517522223) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/src/main.rs#L109)):*
> ```Rust
>             and trace messages with -vv");
>         parser.refer(&mut opts.version)
>             .add_option(&["-V", "--version"], StoreTrue,
> ```

My command line preferences also extend to not having `-v` and `-V`; I think that's just confusing. Having only the long form seems fine.

---

*[src/main.rs, line 119 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxV-_xqlQ1CkSdklWo:-KKxV-_yfSelskPktb1Y:-2003247063) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/src/main.rs#L119)):*
> ```Rust
> 
> fn print_version() {
>     let version = option_env!("CARGO_PKG_VERSION").unwrap_or("unknown");
> ```

Why `option_env!` rather than just `env!`?

---

*[src/main.rs, line 121 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxVHI7tEVRDJ6KwqCR:-KKxVHI7tEVRDJ6KwqCS:-725807443) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/src/main.rs#L121)):*
> ```Rust
>     let version = option_env!("CARGO_PKG_VERSION").unwrap_or("unknown");
>     let hash = COMMIT_HASH.unwrap_or("git commit unavailable");
>     let clean = match WORKTREE_CLEAN {
> ```

I feel like this feature is not worth the added complexity.

---

*[src/main.rs, line 129 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxVM2Ns9M7a0yrygSb:-KKxVM2Ns9M7a0yrygSc:92408994) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/src/main.rs#L129)):*
> ```Rust
> https://github.com/mozilla/geckodriver
> 
> This program is subject to the terms of the Mozilla Public License 2.0.
> ```

FWIW my reading of the license is that including this text is not required. But I guess it's OK.

---

*[src/main.rs, line 207 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxYUJy4CVpgM6Ub9rT:-KKxYUJzsuGq7dRFUK-W:-717217874) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/src/main.rs#L207)):*
> ```Rust
>     std::io::stdout().flush().unwrap();
> 
>     // terminates process without unwinding the stack,
> ```

This comment seems unnecessary, I think? You would have to restructure the code in an odd way to not have run destructors before this point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/109)*

**Comment by jgraham** [comment]
Reviewed 4 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/109)*

**Comment by andreastt** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxRJ3nAKAt69_-ae-V:-KKxasfnnjqjCCa_qE8q:-1601005476) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/src/main.rs#L44)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Feels like this could take a `(ExitCode, String)`
</details>
It could, but I’m concerned we are passing `ExitCode` just for `Ok` and not for `Err`. I can’t really think of a case where a successful `ProgramResult` will be anything other than `ExitCode::Ok`.

---

*[src/main.rs, line 109 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxUTAHUSyG8STQQova:-KKxZiiowxbVzRv7FTBS:280661842) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/src/main.rs#L109)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> My command line preferences also extend to not having `-v` and `-V`; I think that's just confusing. Having only the long form seems fine.
</details>
Yeah, that’s perfectly alright with me. (What command line preferences are these?)

---

*[src/main.rs, line 119 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxV-_xqlQ1CkSdklWo:-KKx_uBeDXXjzGrpeHdN:1446673915) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/src/main.rs#L119)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Why `option_env!` rather than just `env!`?
</details>
`option_env!` produces an `Option<&'static str>` at compile time meaning it won’t fail if the environment variable is missing. This let’s us call `unwrap_or("unknown")` on it so it is always predictable.

I imagine `CARGO_PKG_VERSION` can be empty if you pass a source file directly to rustc.

---

*[src/main.rs, line 121 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxVHI7tEVRDJ6KwqCR:-KKxaH56NEIXHWhMQI1C:-1302944318) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/src/main.rs#L121)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I feel like this feature is not worth the added complexity.
</details>
I was in doubt whether to add it. I don’t have any particular problems with pulling it out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/109)*

**Comment by jgraham** [comment]
Reviewed 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxRJ3nAKAt69_-ae-V:-KKxgLbfeVxSW0Oa5NJJ:1518929313) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/src/main.rs#L44)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> It could, but I’m concerned we are passing `ExitCode` just for `Ok` and not for `Err`. I can’t really think of a case where a successful `ProgramResult` will be anything other than `ExitCode::Ok`.
</details>
I mean the opposite; `Result<(), (ExitCode, String)>`

---

*[src/main.rs, line 109 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxUTAHUSyG8STQQova:-KKxgF5bQRBR3Ov25fk6:1874639099) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/src/main.rs#L109)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> Yeah, that’s perfectly alright with me. (What command line preferences are these?)
</details>
An arbitrary set of irritations I have with other programs being confusing :)

---

*[src/main.rs, line 119 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxV-_xqlQ1CkSdklWo:-KKxfvshtoz5_B55N_3L:1643860034) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/src/main.rs#L119)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> `option_env!` produces an `Option<&'static str>` at compile time meaning it won’t fail if the environment variable is missing. This let’s us call `unwrap_or("unknown")` on it so it is always predictable.
> 
> I imagine `CARGO_PKG_VERSION` can be empty if you pass a source file directly to rustc.
</details>
Right, I think it's OK to not support building without cargo isn't it? I am nervous of silently handling errors and then accidentally releasing binaries with the default values for some reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/109)*

**Comment by andreastt** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxRJ3nAKAt69_-ae-V:-KKxiHNMVda3zHKvvDx4:247146089) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/src/main.rs#L44)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I mean the opposite; `Result<(), (ExitCode, String)>`
</details>
Made the change.

---

*[src/main.rs, line 121 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/109#-KKxVHI7tEVRDJ6KwqCR:-KKxbdnmnjxXO3OpDZVe:-499146009) ([raw file](https://github.com/mozilla/geckodriver/blob/cf2c913599bec436d042a041330884191c4e458b/src/main.rs#L121)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> I was in doubt whether to add it. I don’t have any particular problems with pulling it out.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/109)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/109)*

**Pull request merged**
