### PR TITLE
Cross-compile on win32 using Docker image from port-of-rust

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/213)

### CODE REVIEW

**Comment by andreastt** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 6 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/213#-KQyulOwlScDHtlOs2Tx:-KQyulOwlScDHtlOs2Ty:b-s0pkqn) ([raw file](https://github.com/mozilla/geckodriver/blob/d64a6fbf3977e207eb3940256c61a114fdabfba5/.travis.yml#L6)):*
> ```YAML
>     - $HOME/.cargo
>     - $TRAVIS_BUILD_DIR/target
>     - /home/travis/docker/
> ```

Can be $HOME/travis/docker like the above $HOME/.cargo line, but not essential.

---

*[ci.sh, line 8 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/213#-KQyv9YVfKqyDlT0ANkp:-KQyv9YVfKqyDlT0ANkq:b-vhefwm) ([raw file](https://github.com/mozilla/geckodriver/blob/d64a6fbf3977e207eb3940256c61a114fdabfba5/ci.sh#L8)):*
> ```Shell
>     tag="port-of-rust/$TARGET/latest"
>     docker build https://github.com/alexcrichton/port-of-rust.git -f "$TARGET/Dockerfile" -t $tag
>     docker run -e USER="$USER" -e TARGET="$TARGET" -e USE_DOCKER=1 -e NAME="$NAME" -e TRAVIS_TAG="$TRAVIS_TAG" -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v $PWD:/mnt/host -v $PWD:/mnt/host -i $tag bash -s -- < build.sh
> ```

I think it would be beneficial for readability to break this up into multiple lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/213)*

**Comment by andreastt** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/213)*

**Comment by timaharrison** [comment]
Please accept my apologies if this isn't the right place to ask but I  don't know where else is.  I'm not a developer, but a user of Firefox and Selenium.
Issues 138 and 146 have been merged in to this one, and I was tracking one of these, about geckodriver for 32bit windows.  
I understand that there are difficulties with creating 32bit versions for the Geckodriver, but the situation at the moment is that none of my tests can be run on Firefox, since the original Firefox Driver became obsolete in June.  It is not feasible to change to windows 64bit, nor can I start using old versions of Firefox. I'm sure that many users all over the globe are in the same position unless I'm missing something (please say if I am)
Please can someone say if there is going to be a version for 32bit that works with the most recent Firefox, and if so when we can expect it.
Thanks

**Comment by andreastt** [comment]
@timaharrison We have finished the work to make Windows 32-bit compilation possible in geckodriver’s continuous integration. We have _not_ released a new version yet. You can track the progress of the next release, which will include a 32-bit Windows binary, in https://github.com/mozilla/geckodriver/milestone/1.

**Pull request merged**
