### PR TITLE
Align Send Alert Text property with Element Send Keys property

### PR DESCRIPTION
**Pull request by AutomatedTester**
This simplifies the what we recieve from the local end and then how
we should process it.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/151)

### CODE REVIEW

**Comment by AutomatedTester** [comment]
https://github.com/jgraham/webdriver-rust/pull/39 needs to land first to make this work

**Comment by AutomatedTester** [comment]
The dependency for this has landed, can we get this landed now?

**Comment by andreastt** [comment]
This still fails because the webdriver-rust version hasn’t been upgraded.

**Comment by andreastt** [comment]
https://github.com/mozilla/geckodriver/pull/255

**Comment by AutomatedTester** [comment]
landed

**Pull request closed without merging**
