### PR TITLE
Rename firefoxOptions to moz:firefoxOptions

### LINKED ISSUE #250: Rename firefoxOptions to a key that is spec conformant
However, the WebDriver spec does not yet specify what it should be. I filed https://github.com/w3c/webdriver/issues/341 yesterday.

### PR DESCRIPTION
**Pull request by andreastt**
See https://github.com/w3c/webdriver/pull/343 for further details on
extension capabilities.

Fixes #250.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/251)

### CODE REVIEW

**Comment by andreastt** [comment]
cc @titusfortner @shs96c @lukeis

**Comment by titusfortner** [comment]
We need a colon in the JSON key? Sigh. That'll need to be a special case in the Ruby code.

**Comment by andreastt** [comment]
I don’t understand why that needs to be a special case?

**Comment by titusfortner** [comment]
Because colons aren't allowed in Ruby symbols and right now everything translates :ruby_symbols to 'camelCase' strings, this would be a special case.

**Comment by andreastt** [comment]
That seems like a fragile design as the user can send arbitrary input data in a capability string. Colon and dash are valid JSON.

**Comment by titusfortner** [comment]
Oh, it's just that the place where we verify what is allowed is in a different spot from where we translate it to JSON. Not saying it isn't valid, just voicing my frustrations. I'll make it work. :)

**Comment by andreastt** [comment]
Okay, so the background here is that we need _some way_ to namespace the capabilities to avoid name collisions between vendors and intermediary nodes.

The case with _firefoxOptions_ and _chromeOptions_ is not a big concern as the spec will never specify anything carrying those names, but if intermediaries are allowed to pollute the JSON object we could end up in a situation where we are unable to introduce a new capability in the future.

A concrete example would be if different intermediary nodes expect authentication details and the keys _happen_ to be `{username: …, password: …}`. In this case we need a way for them to be identified uniquely.

**Comment by andreastt** [comment]
Of course there’s nothing stopping you from using `:firefoxOptions` as the internal symbol name in Ruby. 😄

**Comment by titusfortner** [comment]
Right, it will be :chrome_options and :firefox_options that are supported; it'll need to be a special case on the JSON translation end. :)

**Comment by andreastt** [comment]
So a pro-tip, if colon is accepted as the namespace delimiter in https://github.com/w3c/webdriver/pull/343, would be to `key.includes?(":")` to test if it is an extension capability.

**Comment by jgraham** [comment]
FWIW I don't care about the `:` particularly, it could be `-` for example.

**Comment by andreastt** [comment]
I guess https://github.com/w3c/webdriver/pull/343 is a better place to voice opinions on the colour of this bikeshed.

**Comment by titusfortner** [comment]
Go ahead and ignore my complaints. It's a special case either way, and I looked at the code, and it is "easy" for me to deal with either way. Thanks :)

**Comment by jgraham** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/251)*

**Pull request merged**
