### PR TITLE
Fix Windows builds

### LINKED ISSUE #246: Fix 32-bit Windows compile error
https://travis-ci.org/mozilla/geckodriver/builds/163755698

### PR DESCRIPTION
**Pull request by andreastt**
Fixes #246.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/256)

### CODE REVIEW

**Comment by andreastt** [comment]
I think a future improvement to this would be to provide our own Dockerfile descriptions of what we want to build as they are no slower than bare metal builds. This would allow us to move some of the dependency installation out of .travis.yml and build.sh, into the Dockerfiles.

This would particularly benefit one-off components such as the custom mingw thing we need to link for 32-bit Windows.

**Comment by andreastt** [comment]
Anyway, despite the above, I think this solves our immediate problems in no worse way than before.

r? @jgraham

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build.sh, line 28 at r4](https://reviewable.io:443/reviews/mozilla/geckodriver/256#-KTBPZqOMCKSAop-IU6T:-KTBPZqOMCKSAop-IU6U:b-rne29w) ([raw file](https://github.com/mozilla/geckodriver/blob/bd40cf9b4d04d26a316ff844c2bf222a0d7cc174/build.sh#L28)):*
> ```Shell
> 
> mingw_i686_install() {
>     curl https://static.rust-lang.org/dist/rust-mingw-nightly-i686-pc-windows-gnu.tar.gz \
> ```

It's not really clear what this is doing, or why it's only doing it if !DOCKER && i686 (for example it seems like linux32 would not want it, if we added that).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/256)*

**Comment by andreastt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build.sh, line 28 at r4](https://reviewable.io:443/reviews/mozilla/geckodriver/256#-KTBPZqOMCKSAop-IU6T:-KTBQ4azRXFnpJMEifyo:b-w2v4xr) ([raw file](https://github.com/mozilla/geckodriver/blob/bd40cf9b4d04d26a316ff844c2bf222a0d7cc174/build.sh#L28)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> It's not really clear what this is doing, or why it's only doing it if !DOCKER && i686 (for example it seems like linux32 would not want it, if we added that).
</details>
It’s doing it _if_ Docker is being used (`! -z` means _if not undefined_) _and_ i686 is being installed.

But it’s basically what alexcrichton is talking about as the ‘custom `mingw` component’ here: https://github.com/mozilla/geckodriver/pull/138#issuecomment-232139097

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/256)*

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build.sh, line 28 at r4](https://reviewable.io:443/reviews/mozilla/geckodriver/256#-KTBPZqOMCKSAop-IU6T:-KTBSnx8pIcKelJTGePr:b-k4r3i2) ([raw file](https://github.com/mozilla/geckodriver/blob/bd40cf9b4d04d26a316ff844c2bf222a0d7cc174/build.sh#L28)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> It’s doing it _if_ Docker is being used (`! -z` means _if not undefined_) _and_ i686 is being installed.
> 
> But it’s basically what alexcrichton is talking about as the ‘custom `mingw` component’ here: https://github.com/mozilla/geckodriver/pull/138#issuecomment-232139097
</details>
OK, but it seems it should check more of the target to include Windows, and a comment is required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/256)*

**Comment by andreastt** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.sh, line 28 at r4](https://reviewable.io:443/reviews/mozilla/geckodriver/256#-KTBPZqOMCKSAop-IU6T:-KTBVr_1eJpgb51b3zgF:bptzq1s) ([raw file](https://github.com/mozilla/geckodriver/blob/bd40cf9b4d04d26a316ff844c2bf222a0d7cc174/build.sh#L28)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> OK, but it seems it should check more of the target to include Windows, and a comment is required.
</details>
Alright, sorted.

As I said in an earlier comment on the PR, I don’t think this design is optimal. I think we should consider building more (if not everything) in containers and define dependencies, such as the mingw component, in Dockerfiles.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/256)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/256)*

**Pull request merged**
