### PR TITLE
Disable homepage override URL redirection on milestone upgrade

### PR DESCRIPTION
**Pull request by andreastt**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/244)

### CODE REVIEW

**Comment by jgraham** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/marionette.rs, line 79 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/244#-KSqKn-K-XrjNIbo4FOl:-KSqKn-LqDNeSKJ1euIN:b-mhucjj) ([raw file](https://github.com/mozilla/geckodriver/blob/b94f5d50babb22221d2847f90a4aff607f0ba716/src/marionette.rs#L79)):*
> ```Rust
>         ("browser.sessionstore.resume_from_crash", Pref::new(false)),
>         ("browser.shell.checkDefaultBrowser", Pref::new(false)),
>         ("browser.startup.homepage override.mstone", Pref::new("ignore")),
> ```

What does this actually do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/244)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/244)*

**Comment by andreastt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/marionette.rs, line 79 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/244#-KSqKn-K-XrjNIbo4FOl:-KSqL5AzWmCdUL1SLpPu:b-791224) ([raw file](https://github.com/mozilla/geckodriver/blob/b94f5d50babb22221d2847f90a4aff607f0ba716/src/marionette.rs#L79)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> What does this actually do?
</details>
See the commit message: https://github.com/mozilla/geckodriver/pull/244/commits/b94f5d50babb22221d2847f90a4aff607f0ba716

I briefly considered adding a comment to the file itself. Do you think that’s worthwhile?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/244)*

**Pull request merged**
