### PR TITLE
Support the new version of the new session command.

### PR DESCRIPTION
**Pull request by jgraham**
Support the alwaysMatch/firstMatch new session command. Move the
capabilities handling into geckodriver as far as possible so that
marionette itself should not be rejecting sessions (as this is
expensive and can only happen after gecko starts). Use mozversion to
provide (currently somewhat hacky) version number matching for the
browserVersion capability.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/568)

### CODE REVIEW

**Comment by andreastt** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[Cargo.toml, line 22 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg-z3yXWZeRcgmZuv0P:-Kg-z3yYwfC8VUA1KbEA:brcopns) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/Cargo.toml#L22)):*
> ```TOML
> mozprofile = "0.2"
> mozrunner = "0.3"
> mozversion = {"path"="/home/james/develop/mozversion"}
> ```

OK with condition that this is updated before landing patch in geckodriver.

---

*[src/capabilities.rs, line 22 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0LAmsgkIGPeyhUCDu:-Kg0LAmt_2RymhqIUyCu:bv09aia) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L22)):*
> ```Rust
> pub struct FirefoxCapabilities<'a> {
>     pub binary: Option<PathBuf>,
>     settings_binary: Option<&'a PathBuf>,
> ```

Since the binary to use has to be decided based on the capabilities, perhaps this should not make the `binary` field public. 

---

*[src/capabilities.rs, line 27 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0NDIIrCk2iLOSqvPf:-Kg0NDIJ3w9owdv733GC:bbbaema) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L27)):*
> ```Rust
> 
> impl <'a> FirefoxCapabilities<'a> {
>     pub fn new(binary: Option<&'a PathBuf>) -> FirefoxCapabilities<'a> {
> ```

I suggest renaming this `fallback_binary` since that is effectively what it is when `--binary /path/to/firefox` is specified at the command line but overridden by `moz:firefoxOptions`.

---

*[src/capabilities.rs, line 35 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0MNohcXI1Hr_b5sdW:-Kg0MNoivBmwpPpEmw-1:b7wwb5c) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L35)):*
> ```Rust
>     }
> 
>     pub fn binary_path(&self, capabilities: &BTreeMap<String, Json>) -> Option<PathBuf> {
> ```

I think this should have a more descriptive name as I had trouble tracing what was going on here. Maybe `resolve_binary` or `decide_binary`: the idea is that it takes the capabilities and chooses the Firefox binary provided there, falls back to the one set at the command-line, and then finally falls back to the default system Firefox (if any).

I do think it is slightly confusing that `FirefoxCapabilities` has a public `binary` field that isn’t set until `init(capabilities)` is called. If that were to go this could probably keep its name.

---

*[src/capabilities.rs, line 74 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0GfEwyp4B_1oM4nfk:-Kg0GfEwyp4B_1oM4nfl:br11ocw) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L74)):*
> ```Rust
>             Some("windows".into())
>         } else if cfg!(target_os="macos") {
>             Some("macos".into())
> ```

Should be `mac` according to spec.

---

*[src/capabilities.rs, line 78 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0P-h6mJYl2JlGl7nu:-Kg0P-h76YE5BT9JQp7h:bma4z5g) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L78)):*
> ```Rust
>             Some("linux".into())
>         } else {
>             None
> ```

This should ideally return `target_os` at runtime, but I’m not sure how to attain it.

---

*[src/capabilities.rs, line 83 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0His0lNvB_YMsDdNR:-Kg0His0lNvB_YMsDdNS:bg4z1bs) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L83)):*
> ```Rust
> 
>     fn accept_insecure_certs(&mut self, _: &BTreeMap<String, Json>) -> WebDriverResult<bool> {
>         Ok(true)
> ```

Only true for Firefox 52 onwards (https://bugzilla.mozilla.org/show_bug.cgi?id=1103196), so as we have access to the version number we could return true/false based on a comparison here.

---

*[src/capabilities.rs, line 105 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0IIL5IkJHDnXezaXS:-Kg0IIL5IkJHDnXezaXT:bi4q1gg) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L105)):*
> ```Rust
>                 let data = try_opt!(value.as_object(),
>                                     ErrorStatus::InvalidArgument,
>                                     "moz:firefoxOptions was not an object");
> ```

s/was/is/g throughout

---

*[src/capabilities.rs, line 112 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0IF6k3tcygI4H7Iyp:-Kg0IF6lCnT_cjJqv4Mk:b-ep18xd) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L112)):*
> ```Rust
>                                 return Err(WebDriverError::new(
>                                     ErrorStatus::InvalidArgument,
>                                          "binary path was not an object"));
> ```

s/object/string/

---

*[src/capabilities.rs, line 150 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0Ia3ifaSF5KLfqN71:-Kg0Ia3ifaSF5KLfqN72:b-us9g5q) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L150)):*
> ```Rust
>                                                 format!("{} is not a valid log level",
>                                                         level)))
>                                         }
> ```

You can reuse `logging::LogLevel::from_str` here: https://github.com/mozilla/geckodriver/blob/master/src/logging.rs#L54

---

*[src/capabilities.rs, line 162 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0IvazD5TjAudtzroe:-Kg0Ivb-hwZ6Ob7DLpJz:b15tje2) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L162)):*
> ```Rust
>                                                     ErrorStatus::InvalidArgument,
>                                                     "prefs value was not an object");
>                             if !prefs_data.values()
> ```

Missing check for string keys?

---

*[src/capabilities.rs, line 166 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0J7ttX07_H5yuDTUy:-Kg0J7ttX07_H5yuDTUz:bf8p2fd) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L166)):*
> ```Rust
>                                     return Err(WebDriverError::new(
>                                         ErrorStatus::InvalidArgument,
>                                         "pref values not all string or integer or boolean"));
> ```

s/pref/Preference/

---

*[src/capabilities.rs, line 176 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0JBJCQwVITgkT1Crb:-Kg0JBJCQwVITgkT1Crc:bnouttg) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L176)):*
> ```Rust
>             }
>             _ => return Err(WebDriverError::new(ErrorStatus::InvalidArgument,
>                                                 format!("Unrecognised option {:}", name)))
> ```

What does `{:}` do here compared to `{}`?

---

*[src/capabilities.rs, line 200 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0JICpenOJVFJHV4dC:-Kg0JICqOcom8YBb1hLw:b-ox6ntp) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L200)):*
> ```Rust
>                              -> WebDriverResult<FirefoxOptions> {
> 
>         let mut rv: FirefoxOptions = Default::default();
> ```

`let mut rv = FirefoxOptions::new()` look better IMO.

---

*[src/marionette.rs, line 282 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg00ekhJp5quRljsoxs:-Kg00ekhJp5quRljsoxt:b-3xyq98) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/marionette.rs#L282)):*
> ```Rust
>                     .ok_or(WebDriverError::new(
>                         ErrorStatus::SessionNotCreated,
>                         "Unable to find a matching set of capabilities.")));
> ```

Drop trailing full stop in error messages.

---

*[src/marionette.rs, line 839 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0K0bC56SUrqPBlKZF:-Kg0K0bC56SUrqPBlKZG:br48wgu) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/marionette.rs#L839)):*
> ```Rust
>                 data.insert("capabilities".to_string(),
>                             desired_capabilites.to_json());
>                 (Some("newSession"), Some(Ok(data)))
> ```

Can we make this also send `capabilities` as a top-level entry for forward compatibility? I’d quite like to remove parsing of `{capabilities: …}` at some point in the future from Marionette.

I am thinking like this:

```js
{
    capabilities: {
         desiredCapabilities: {
             acceptInsecureCerts: true,
             …
         }
    },
    acceptInsecureCerts: true,
}
```

---

*[src/marionette.rs, line 1188 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0Ki5KfnHs-qSnhD7k:-Kg0Ki5KfnHs-qSnhD7l:b59bwm6) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/marionette.rs#L1188)):*
> ```Rust
> 
>     pub fn send_command(&mut self,
>                         capabilities: Option<BTreeMap<String, Json>>,
> ```

I think it’s not entirely right that we should have to pass the capabilities every time we have to send a command or decode the message, but I don’t know if there’s a better solution?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/568)*

**Comment by andreastt** [comment]
Reviewed 2 of 5 files at r1.
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/568)*

**Comment by jgraham** [comment]
Review status: 1 of 5 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[src/capabilities.rs, line 22 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0LAmsgkIGPeyhUCDu:-KgFFh_MjoE3iyim19cZ:b-rnhgak) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L22)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary><blockquote>

Since the binary to use has to be decided based on the capabilities, perhaps this should not make the `binary` field public. 
</blockquote></details>

OK, so. That's difficult. Because what happens here is we iterate through the capabilities setting this field until we find one that matches. At that point the last set binary is the one that we use. It's probably not amazing design, but there we go.

---

*[src/capabilities.rs, line 35 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0MNohcXI1Hr_b5sdW:-KgFFxhe-MydCh0uHLqj:b-jpxxg1) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L35)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary><blockquote>

I think this should have a more descriptive name as I had trouble tracing what was going on here. Maybe `resolve_binary` or `decide_binary`: the idea is that it takes the capabilities and chooses the Firefox binary provided there, falls back to the one set at the command-line, and then finally falls back to the default system Firefox (if any).

I do think it is slightly confusing that `FirefoxCapabilities` has a public `binary` field that isn’t set until `init(capabilities)` is called. If that were to go this could probably keep its name.
</blockquote></details>

I changed this a little, I hope it makes more sense now.

---

*[src/capabilities.rs, line 78 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0P-h6mJYl2JlGl7nu:-KgFG21BW3PRAoeZrT6b:boqk0sb) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L78)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary><blockquote>

This should ideally return `target_os` at runtime, but I’m not sure how to attain it.
</blockquote></details>

I'm happy to not support that for now.

---

*[src/capabilities.rs, line 162 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0IvazD5TjAudtzroe:-KgFG99822nJqFSsk-hw:b-utgq5) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L162)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary><blockquote>

Missing check for string keys?
</blockquote></details>

Json object keys are always strings.

---

*[src/marionette.rs, line 839 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0K0bC56SUrqPBlKZF:-KgFGEx529xSXubRgQDf:bhiocv6) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/marionette.rs#L839)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary><blockquote>

Can we make this also send `capabilities` as a top-level entry for forward compatibility? I’d quite like to remove parsing of `{capabilities: …}` at some point in the future from Marionette.

I am thinking like this:

```js
{
    capabilities: {
         desiredCapabilities: {
             acceptInsecureCerts: true,
             …
         }
    },
    acceptInsecureCerts: true,
}
```
</blockquote></details>

I don't understand what you mean.

---

*[src/marionette.rs, line 1188 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0Ki5KfnHs-qSnhD7k:-KgFGILC3Lb45aLQEbRA:bf3e6r0) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/marionette.rs#L1188)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary><blockquote>

I think it’s not entirely right that we should have to pass the capabilities every time we have to send a command or decode the message, but I don’t know if there’s a better solution?
</blockquote></details>

Well the only other solution would be to route the new session command through a totally different codepath, or have another wrapper enum like `enum {NewSession(Capabilities, Command), Other(Command)} . In the current design we usually send `None` as the capabilities, except for `NewSession`. It's obviously a pretty terrible design, but it was the smallest change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/568)*

**Comment by andreastt** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[Cargo.toml, line 22 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-KgFIXUiQwwn2sHn4Nvn:-KgFIXUjKhNrxhyWCYxv:b1wfkto) ([raw file](https://github.com/mozilla/geckodriver/blob/b0b65a640fe4a6f79242f777a4779126879496a1/Cargo.toml#L22)):*
> ```TOML
> mozprofile = "0.2"
> mozrunner = "0.3"
> mozversion = {"path"="/home/james/develop/mozversion"}
> ```

Update to point to crates.io.

---

*[Cargo.toml, line 30 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-KgFIZrjQ_85LiZRfcWn:-KgFIZrjQ_85LiZRfcWo:b-k1eu2t) ([raw file](https://github.com/mozilla/geckodriver/blob/b0b65a640fe4a6f79242f777a4779126879496a1/Cargo.toml#L30)):*
> ```TOML
> slog-stream = "1"
> uuid = "0.1.18"
> webdriver = {"path"="/home/james/develop/webdriver-rust"}
> ```

Update to 0.24.

---

*[src/capabilities.rs, line 22 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0LAmsgkIGPeyhUCDu:-KgFIp3E27QCti-38AdY:b2nhktp) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L22)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

OK, so. That's difficult. Because what happens here is we iterate through the capabilities setting this field until we find one that matches. At that point the last set binary is the one that we use. It's probably not amazing design, but there we go.
</blockquote></details>

OK.

---

*[src/capabilities.rs, line 35 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0MNohcXI1Hr_b5sdW:-KgFJ6pIZbrcwYTCtPtx:b-gjr1v) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L35)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I changed this a little, I hope it makes more sense now.
</blockquote></details>

New names are better. Thanks!

---

*[src/capabilities.rs, line 78 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0P-h6mJYl2JlGl7nu:-KgFNAHJr4sK9rJTYhL-:b-pbdqz3) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L78)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I'm happy to not support that for now.
</blockquote></details>

Agreed.

---

*[src/capabilities.rs, line 83 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0His0lNvB_YMsDdNR:-KgFN689QVbenI77rTdQ:b-ob67a5) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L83)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary><blockquote>

Only true for Firefox 52 onwards (https://bugzilla.mozilla.org/show_bug.cgi?id=1103196), so as we have access to the version number we could return true/false based on a comparison here.
</blockquote></details>

Thanks! It’s also good to see mozversion in action.

---

*[src/capabilities.rs, line 162 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0IvazD5TjAudtzroe:-KgFMqKHemj_P8u6kTkW:b-v90qin) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L162)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Json object keys are always strings.
</blockquote></details>

I don’t know what I was thinking here.

---

*[src/capabilities.rs, line 33 at r2](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-KgFIv-eEoHxPq9z61cD:-KgFIv-eEoHxPq9z61cE:bolwj2l) ([raw file](https://github.com/mozilla/geckodriver/blob/b0b65a640fe4a6f79242f777a4779126879496a1/src/capabilities.rs#L33)):*
> ```Rust
>             chosen_binary: None,
>             fallback_binary: fallback_binary,
>             version_cache: BTreeMap::new()
> ```

This reads much better now. Thanks!

---

*[src/marionette.rs, line 839 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0K0bC56SUrqPBlKZF:-KgFJbF-ZtvrEerBcYpS:bmkj98q) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/marionette.rs#L839)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I don't understand what you mean.
</blockquote></details>

geckodriver currently sends `{capabilities: desiredCapabilities: {…}}` to Marionette. The long-term vision is for Marionette to only accept a dictionary of settings and for geckodriver to do the capabilities negotiation. This patch implements the latter.

In an effort to keep the Marionette code clean, I’d like to remove extraction of said settings from the `desiredCapabilities` level of the dictionary. Could we, for backwards compatibility reasons, duplicate the settings at the top-level of the overall JSON Object so that we at some point in the future can remove the `capabilities` and `desiredCapabilities` fields from geckodriver?

The example I include in my first comment is an example of what it would look like. If we send that to Marionette, it can prefer the outer settings values and fall back to look in `capabilities` → `desiredCapabilities`. This would be backwards compatible with older Firefoxen.

---

*[src/marionette.rs, line 1188 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0Ki5KfnHs-qSnhD7k:-KgFMYBkoOVVCjeiYXbe:b2nhktp) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/marionette.rs#L1188)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Well the only other solution would be to route the new session command through a totally different codepath, or have another wrapper enum like `enum {NewSession(Capabilities, Command), Other(Command)} . In the current design we usually send `None` as the capabilities, except for `NewSession`. It's obviously a pretty terrible design, but it was the smallest change.
</blockquote></details>

OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/568)*

**Comment by andreastt** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/capabilities.rs, line 112 at r1](https://reviewable.io:443/reviews/mozilla/geckodriver/568#-Kg0IF6k3tcygI4H7Iyp:-KgFNxrz-Qrk986MjviZ:b-896fix) ([raw file](https://github.com/mozilla/geckodriver/blob/949cd62a5aa56f91cb1b8cd4f9ad822e7dbc3fd2/src/capabilities.rs#L112)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary><blockquote>

s/object/string/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/568)*

**Pull request merged**
