### PR TITLE
Send Keys now accepts a string to be passed on to Marionette

### PR DESCRIPTION
**Pull request by AutomatedTester**
This is the other half of https://github.com/mozilla/webdriver-rust/pull/80

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/553)

### CODE REVIEW

**Comment by AutomatedTester** [comment]
This will need a webdriver-rust release before merging

**Comment by AutomatedTester** [comment]
And requires https://bugzilla.mozilla.org/show_bug.cgi?id=1348782 be landed and uplifted

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/553)*

**Comment by jgraham** [comment]
Just wating for the webdriver-rust release.

**Comment by andreastt** [comment]
Merged in https://github.com/mozilla/geckodriver/commit/9d76e0bd498263540fdaa4a8a18f084eb0dfd9bd.

**Pull request closed without merging**
