### PR TITLE
Connect between geckodriver and marionette on a random port.

### PR DESCRIPTION
**Pull request by jgraham**
This allows running multiple sessions without needing to reuse the
same port.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/112)

### CODE REVIEW

**Comment by andreastt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main.rs, line 238 \[r2\]](https://reviewable.io:443/reviews/mozilla/geckodriver/112#-KL1JPDVHOjLJY6rmdCo:-KL1JPDVHOjLJY6rmdCp:-406342216) ([raw file](https://github.com/mozilla/geckodriver/blob/b61b2ecbf249122d28606fb001f4f3f3f898ee08/src/main.rs#L238)):*
> ```Rust
> 
>         let mut gecko_profile = handler.load_profile(&capabilities).unwrap().unwrap();
>         handler.set_prefs(2828, &mut gecko_profile, true).unwrap();
> ```

Make this a constant

---

*[src/marionette.rs, line 322 \[r2\]](https://reviewable.io:443/reviews/mozilla/geckodriver/112#-KL1J8nz0XBf9NKFyzqU:-KL1J8o-Snkycpc46jry:559962442) ([raw file](https://github.com/mozilla/geckodriver/blob/b61b2ecbf249122d28606fb001f4f3f3f898ee08/src/marionette.rs#L322)):*
> ```Rust
>             None => try!(MarionetteConnection::get_free_port())
>         };
>         info!("Using port {} for marionette connection", port);
> ```

Can we log this later, when actually attempting to connect to Marionette? Like, `Connecting to Marionette on localhost:1234`.

---

*[src/marionette.rs, line 1112 \[r2\]](https://reviewable.io:443/reviews/mozilla/geckodriver/112#-KL1J_xyvyt4d5lBg47v:-KL1J_xzrJZ8LldoR8TF:465226161) ([raw file](https://github.com/mozilla/geckodriver/blob/b61b2ecbf249122d28606fb001f4f3f3f898ee08/src/marionette.rs#L1112)):*
> ```Rust
>             .and_then(|stream| stream.local_addr())
>             .map(|x| x.port())
>     }
> ```

Can we make this an private function on the file level instead of a published function on the object?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/112)*

**Comment by andreastt** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/112)*

**Comment by andreastt** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/marionette.rs, line 1118 \[r3\]](https://reviewable.io:443/reviews/mozilla/geckodriver/112#-KLHsjJYz0Y_4OVVhP4u:-KLHsjJYz0Y_4OVVhP4v:246437345) ([raw file](https://github.com/mozilla/geckodriver/blob/e97cfd563d568c888e0d67e1d5d3d076923a149f/src/marionette.rs#L1118)):*
> ```Rust
>         let poll_attempts = timeout / poll_interval;
>         let mut poll_attempt = 0;
>         info!("Connecting to marionette on localhost:{}", self.port);
> ```

s/marionette/Marionette/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/112)*

**Comment by jreiher2003** [comment]
I  have tried connecting on firefox over tor with javascript disabled, and it still seems to be an issue.

**Comment by andreastt** [comment]
@jreiher2003 I don’t understand. What problem are you having?

**Pull request merged**
