### PR TITLE
Send quitApplication command when deleting a session.

### PR DESCRIPTION
**Pull request by jgraham**
r? @AutomatedTester

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/70)

### CODE REVIEW

**Comment by andreastt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/marionette.rs, line 794 \[r1\]](https://reviewable.io:443/reviews/mozilla/geckodriver/70#-KJa4JkyljIH4_xDI4jN:-KJa4JkyljIH4_xDI4jO:662575706) ([raw file](https://github.com/mozilla/geckodriver/blob/f454c0d2172d25abfc34cd88f56849ac71ebb0bd/src/marionette.rs#L794)):*
> ```Rust
>                 body.insert("flags".to_owned(), vec!["eForceQuit".to_json()].to_json());
>                 (Some("quitApplication"), Some(Ok(body)))
>             },
> ```

I believe the [implementation in Marionette](https://github.com/mozilla/gecko-dev/blob/master/testing/marionette/driver.js#L2297) of [Delete Session](http://w3c.github.io/webdriver/webdriver-spec.html#delete-session) is wrong, but I suppose it depends on what granularity you want the Marionette protocol to have.

According to WebDriver, calling _Delete Session_ should close all top-level browsing contexts and cause the browser process to quit. Marionette just terminates the session and leaves the browser running currently.

I ran into this problem when working on the wdspec tests, so causing Firefox to quit when the session is deleted is very much a welcome change. However, I feel this should be fixed in Marionette unless there are any particularly good reasons in testing Firefox where we need to delete session _without_ quitting the browser.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/70)*

**Comment by andreastt** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/70)*

**Comment by andreastt** [comment]
@jgraham So what do you think? Fix it in Marionette, push to try, and see what breaks?

**Comment by jgraham** [comment]
I have zero confidence that nothing in Fx UI tests or similar will break if the behaviour of delete_session is changed. I mean I guess I can run the experiment, but just changing the clients one at a time is an appealing way of doing this incrementally.

**Comment by andreastt** [comment]
I can run the tests, but the session lifetime in the Firefox UI tests should in theory be managed by the Marionette test runner. This, in theory, only calls `Marionette:deleteSession` at the end of the test suite.

**Comment by andreastt** [comment]
I looked into this in more detail and concluded that the Marionette harness in mozilla-central is too tightly coupled to the idea that deleting a session _should not_ quit the browser, that it makes little sense to put in the effort of untangling it.

I support making geckodriver call `Marionette:deleteSession` and then `Marionette:quitApplication` to patch over this problem.

**Comment by andreastt** [comment]
:lgtm:

<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> I looked into this in more detail and concluded that the Marionette harness in mozilla-central is too tightly coupled to the idea that deleting a session _should not_ quit the browser, that it makes little sense to put in the effort of untangling it.
> 
> 
> 
> I support making geckodriver call `Marionette:deleteSession` and then `Marionette:quitApplication` to patch over this problem.
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/geckodriver/70#-:-KJax3HCTPD9OFINAy4Q:1417088721)*

**Pull request merged**
