### PR TITLE
Accept "page load" as an alternative spelling of "pageLoad" in the Ge…

### PR DESCRIPTION
**Pull request by juangj**
…t Timeouts response.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/geckodriver/656)

### CODE REVIEW

**Comment by juangj** [comment]
(Because https://bugzilla.mozilla.org/show_bug.cgi?id=1342162 is not present in 52.)

Are there tests I should be writing somewhere for this?

**Comment by andreastt** [comment]
I feel that the right approach for this would be to fix the Selenium clients. As I understand it, the expectation is that only the most recent release of Selenium will work with geckodriver, so why can’t we fix the clients there instead?

**Comment by juangj** [comment]
I don't think this is a Selenium problem -- it's a problem with communication between Geckodriver and Marionette.

Here's a sample log: [geckodriver.log.txt](https://github.com/mozilla/geckodriver/files/938798/geckodriver.log.txt)

The relevant excerpt:
```
1492640392727	webdriver::server	DEBUG	Got request GET AbsolutePath("/session/2f4c3ef2-0854-4e02-8c73-626666141d8f/timeouts")
1492640392727	geckodriver::marionette	TRACE	→ 22:[0,3,"getTimeouts",{}]
1492640392728	Marionette	TRACE	conn0 -> [0,3,"getTimeouts",{}]
1492640392728	Marionette	TRACE	conn0 <- [1,3,null,{"implicit":0,"page load":300000,"script":30000}]
1492640392729	geckodriver::marionette	TRACE	← [1,3,null,{"implicit":0,"page load":300000,"script":30000}]
1492640392729	webdriver::server	DEBUG	Returning status InternalServerError
1492640392729	webdriver::server	DEBUG	Returning body {"value":{"error":"unknown error","message":"Missing field: pageLoad","stacktrace":"stack backtrace:\n   0:           0x4eff6d - backtrace::backtrace::trace::h45ace4059cd74233\n   1:           0x4f0452 - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc\n   2:           0x443d0f - geckodriver::marionette::MarionetteSession::response::h6735ed524e4fc82f\n   3:           0x41fc8e - <webdriver::server::Dispatcher<T, U>>::run::h92d0abd046b7a5de\n   4:           0x40a6b2 - std::panicking::try::do_call::hd524dd132d0c3fae\n   5:           0x5abada - panic_unwind::__rust_maybe_catch_panic\n                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libpanic_unwind/lib.rs:98\n   6:           0x416617 - <F as alloc::boxed::FnBox<A>>::call_box::h80fb3621e7b42042\n   7:           0x5a42f4 - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc/boxed.rs:624\n                         - std::sys_common::thread::start_thread\n                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys/unix/thread.rs:84"}}
```

**Comment by andreastt** [comment]
Right, I misread your patch: it looks for the `pageLoad` field in the response from Marionette, and if that doesn’t exist, `page load`, before returning the spec-conforming timeout configuration object containing `pageLoad` to the client.

Because some Firefox versions found in the live return `page load` and some `pageLoad`, patching over this protocol inconsistency in geckodriver is a neat solution.

Normally I don’t feel we should do backwards compatibility fixing for anything older than stable, but I think the 52 ESR could be considered an exception since quite a lot of effort was spent preparing it for Selenium and a lot of our users appear to be on it.

**Comment by andreastt** [comment]
Thanks for the patch, and sorry for the initial confusion.

**Comment by juangj** [comment]
NP, thanks for the quick replies. I do agree in general that the backwards-compatibility fix is a little icky, but unless/until the fix gets into the ESR version, it seems like the lesser of two evils.

**Pull request merged**
